import {
  IconBrandGoogle,
  IconBrandGithub,
  IconBrandOpenai,
  IconBrandX,
  IconBrain,
  IconCode,
  IconSparkles,
} from '@tabler/icons-react';
import type { LlmProviderOption } from './components/LlmProviderApiKeyFields';

export type AssistantSubscriptionProviderOption = LlmProviderOption & {
  authKind: 'device_code' | 'setup_token' | 'plan_key';
  credentialLabel?: string;
  credentialPlaceholder?: string;
  guideTitle: string;
  guideDescription: string;
  guideSteps: readonly string[];
  guideUrl: string;
};

export const ASSISTANT_PROVIDER_OPTIONS = [
  {
    value: 'kimi',
    label: 'Kimi For Coding',
    defaultModel: 'kimi/kimi-for-coding',
    icon: IconSparkles,
  },
  {
    value: 'moonshot',
    label: 'Moonshot Kimi',
    defaultModel: 'moonshot/kimi-k2.6',
    icon: IconSparkles,
  },
  {
    value: 'openai',
    label: 'OpenAI',
    defaultModel: 'openai/gpt-5.6',
    icon: IconBrandOpenai,
  },
  {
    value: 'anthropic',
    label: 'Anthropic Claude',
    defaultModel: 'anthropic/claude-opus-4-6',
    icon: IconBrain,
  },
  {
    value: 'google',
    label: 'Google Gemini',
    defaultModel: 'google/gemini-3.1-pro-preview',
    icon: IconBrandGoogle,
  },
  {
    value: 'openrouter',
    label: 'OpenRouter',
    defaultModel: 'openrouter/auto',
    icon: IconCode,
  },
  {
    value: 'deepseek',
    label: 'DeepSeek',
    defaultModel: 'deepseek/deepseek-v4-flash',
    icon: IconBrain,
  },
  {
    value: 'xai',
    label: 'xAI Grok',
    defaultModel: 'xai/grok-4.3',
    icon: IconBrandX,
  },
  {
    value: 'zai',
    label: 'GLM (Z.AI)',
    defaultModel: 'zai/glm-5.2',
    icon: IconBrain,
  },
] as const satisfies readonly LlmProviderOption[];

export const getManagedAssistantModel = (provider?: string | null) => {
  const normalizedProvider = provider?.trim().toLowerCase() || 'kimi';

  return (
    ASSISTANT_PROVIDER_OPTIONS.find(({ value }) => value === normalizedProvider)
      ?.defaultModel || ASSISTANT_PROVIDER_OPTIONS[0].defaultModel
  );
};

export const ASSISTANT_SUBSCRIPTION_PROVIDER_OPTIONS = [
  {
    value: 'openai',
    label: 'ChatGPT',
    defaultModel: 'openai/gpt-5.6-sol',
    icon: IconBrandOpenai,
    authKind: 'device_code',
    guideTitle: 'Connect your ChatGPT subscription',
    guideDescription:
      'Use the OpenAI account that owns your ChatGPT plan. OpenClaw uses Codex subscription OAuth, not an OpenAI API key.',
    guideSteps: [
      'Select Connect subscription when the assistant connection screen opens.',
      'Open the OpenAI sign-in page shown by Erxes and enter the one-time code.',
      'Sign in with the ChatGPT account that owns the plan and approve access.',
    ],
    guideUrl: 'https://docs.openclaw.ai/providers/openai',
  },
  {
    value: 'anthropic',
    label: 'Claude',
    defaultModel: 'anthropic/claude-sonnet-4-6',
    icon: IconBrain,
    authKind: 'setup_token',
    credentialLabel: 'Claude setup-token',
    credentialPlaceholder: 'Paste the Claude setup-token',
    guideTitle: 'Connect your Claude subscription',
    guideDescription:
      'Claude Pro and Max authenticate through a setup-token generated by Claude Code. The $20 Pro plan uses the subscription-compatible Sonnet model.',
    guideSteps: [
      'Install or update Claude Code on your own computer.',
      'Run claude and sign in with the account that owns your Claude Pro or Max plan.',
      'Run claude setup-token, then paste the generated token below.',
    ],
    guideUrl: 'https://docs.openclaw.ai/oauth',
  },
  {
    value: 'github-copilot',
    label: 'GitHub Copilot',
    defaultModel: 'github-copilot/claude-opus-4.7',
    icon: IconBrandGithub,
    authKind: 'device_code',
    guideTitle: 'Connect your GitHub Copilot subscription',
    guideDescription:
      'Use a GitHub account with an active Copilot plan. Available models follow that account’s Copilot entitlement.',
    guideSteps: [
      'Select Connect subscription when the assistant connection screen opens.',
      'Open the GitHub device page shown by Erxes and enter the one-time code.',
      'Authorize OpenClaw with the GitHub account that owns the Copilot plan.',
    ],
    guideUrl: 'https://docs.openclaw.ai/providers/github-copilot',
  },
  {
    value: 'minimax-portal',
    label: 'MiniMax Coding Plan',
    defaultModel: 'minimax-portal/MiniMax-M3',
    icon: IconSparkles,
    authKind: 'device_code',
    guideTitle: 'Connect your MiniMax Coding Plan',
    guideDescription:
      'OpenClaw connects to the global MiniMax Coding Plan through MiniMax OAuth. No MiniMax API key is required.',
    guideSteps: [
      'Confirm that the MiniMax account has an active Coding Plan.',
      'Select Connect subscription when the assistant connection screen opens.',
      'Open the MiniMax authorization page shown by Erxes and approve access.',
    ],
    guideUrl: 'https://docs.openclaw.ai/providers/minimax',
  },
  {
    value: 'qwen',
    label: 'Qwen Coding Plan',
    defaultModel: 'qwen/qwen3.7-plus',
    icon: IconCode,
    authKind: 'plan_key',
    credentialLabel: 'Qwen Coding Plan key',
    credentialPlaceholder: 'Paste the global Qwen Coding Plan key',
    guideTitle: 'Connect your Qwen Coding Plan',
    guideDescription:
      'Use the key issued for the global Qwen Cloud Coding Plan. This is separate from the Standard pay-as-you-go API service.',
    guideSteps: [
      'Activate a global Qwen Cloud Coding Plan.',
      'Open the Qwen Cloud Coding Plan key page and copy the key attached to the plan.',
      'Paste that Coding Plan key below; Erxes sends it only to this assistant runtime.',
    ],
    guideUrl: 'https://docs.openclaw.ai/providers/qwen',
  },
  {
    value: 'zai',
    label: 'Z.AI GLM Coding Plan',
    defaultModel: 'zai/glm-5.2',
    icon: IconBrain,
    authKind: 'plan_key',
    credentialLabel: 'Z.AI Coding Plan key',
    credentialPlaceholder: 'Paste the global Z.AI Coding Plan key',
    guideTitle: 'Connect your Z.AI GLM Coding Plan',
    guideDescription:
      'Use a key from the global Z.AI GLM Coding Plan. OpenClaw routes it to the subscription endpoint instead of general API billing.',
    guideSteps: [
      'Activate a global Z.AI GLM Coding Plan.',
      'Copy the key shown for the Coding Plan in the Z.AI console.',
      'Paste the Coding Plan key below; Erxes sends it only to this assistant runtime.',
    ],
    guideUrl: 'https://docs.openclaw.ai/providers/zai',
  },
] as const satisfies readonly AssistantSubscriptionProviderOption[];

export const getSubscriptionProviderOption = (
  provider?: string | null,
): AssistantSubscriptionProviderOption => {
  const normalizedProvider = provider?.trim().toLowerCase() || 'openai';

  return (
    ASSISTANT_SUBSCRIPTION_PROVIDER_OPTIONS.find(
      ({ value }) => value === normalizedProvider,
    ) || ASSISTANT_SUBSCRIPTION_PROVIDER_OPTIONS[0]
  );
};

export const subscriptionProviderUsesDeviceCode = (
  provider?: string | null,
) => getSubscriptionProviderOption(provider).authKind === 'device_code';

export const subscriptionProviderNeedsCredential = (
  provider?: string | null,
) => getSubscriptionProviderOption(provider).authKind !== 'device_code';

export const getSubscriptionAssistantModel = (provider?: string | null) => {
  return getSubscriptionProviderOption(provider).defaultModel;
};
