export const REGISTRATION_ACTIVITY_CATEGORY_OPTIONS = [
  { value: '12.1.1', label: '12.1.1 — Гадагш аялал' },
  { value: '12.1.2', label: '12.1.2 — Дотогш аялал' },
  { value: '12.1.3', label: '12.1.3 — Олон улсын хосолсон аялал' },
  { value: '12.1.4', label: '12.1.4 — Дотоодын аялал' },
  { value: 'hotel', label: 'Зочид буудал (Hotel)' },
  { value: 'resort', label: 'Ресорт (Resort)' },
  { value: 'lodge', label: 'Лож (Lodge)' },
  { value: 'tourist_base', label: 'Жуулчны бааз' },
  { value: 'resort_area', label: 'Амралтын газар' },
  { value: 'inn', label: 'Дэн буудал' },
  { value: 'guest_house', label: 'Гэст хаус (Guest House)' },
  { value: 'transport', label: 'Тээвэр' },
  { value: 'food_production', label: 'Хоол үйлдвэрлэл' },
  { value: 'leisure', label: 'Амралт зугаалгын' },
  { value: 'adventure', label: 'Адал явдалт' },
  { value: 'cultural', label: 'Соёлын' },
  { value: 'eco', label: 'Эко' },
  { value: 'wellness', label: 'Эрүүл мэндийн' },
  { value: 'business', label: 'Бизнесийн' },
  { value: 'religious_ceremony', label: 'Шашны зан үйлийн' },
  { value: 'sports', label: 'Спортын' },
  { value: 'food', label: 'Хоолны' },
  { value: 'education', label: 'Боловсролын' },
  { value: 'border', label: 'Хил орчмын' },
  { value: 'special_needs', label: 'Тусгай хэрэгцээт' },
  { value: 'volunteer', label: 'Сайн дурын' },
  { value: 'special_interest', label: 'Тусгай сонирхлын' },
] as const;
